
from google_play_scraper.scraper import PlayStoreScraper
from common_apk_module import * 

files_needed_list = ["Adobe Acrobat Reader.apk",
                     "Airbnb.apk",
                     "Akinator.apk",
                     "Akinator VIP.apk",
                     "Amazon.apk",
                     "Amazon Music.apk",
                     "Amazon Prime Video.apk",
                     "American Airlines.apk",
                     "Among Us.apk",
                     "Android Accessibility Suite.apk",
                     "Android System WebView.apk",
                     "Angry Birds 2.apk",
                     "ANT Radio Service.apk",
                     "ANT+ Plugins Service.apk",
                     "Bank of America.apk",
                     "Beautiful Widgets Pro.apk",
                     "BitLife.apk",
                     "Bloons TD 6.apk",
                     "Bridge Constructor.apk",
                     "Buff Knight Advanced - Retro RPG Runner.apk",
                     "Bumble.apk",
                     "Camera ZOOM FX Premium.apk",
                     "CampusGroups.apk",
                     "Candy Crush Saga.apk",
                     "Canvas Student.apk",
                     "Canvas Teacher.apk",
                     "Cash App.apk",
                     "Chase.apk",
                     "Clash of Clans.apk",
                     "Clubhouse.apk",
                     "Coin Princess VIP: Retro RPG Quest.apk",
                     "Coinbase.apk",
                     "Construction Simulator 3.apk",
                     "Craigslist.apk",
                     "Crunchyroll.apk",
                     "Crypto.com.apk",
                     "Cut the Rope GOLD.apk",
                     "DailyArt.apk",
                     "Device Care.apk",
                     "Discord.apk",
                     "Discovery+.apk",
                     "Disney+.apk",
                     "DoorDash.apk",
                     "DraStic DS Emulator.apk",
                     "Draw Something.apk",
                     "Dropbox.apk",
                     "Dungeon Defense.apk",
                     "Duo Mobile.apk",
                     "Duolingo.apk",
                     "Dutch Bros.apk",
                     "Earn to Die.apk",
                     "Ebay.apk",
                     "Empire Warriors Premium: Tactical TD Game.apk",
                     "EoSFitness.apk",
                     "Evil Apples.apk",
                     "Facebook.apk",
                     "Facebook Lite.apk",
                     "Firefox.apk",
                     "Fitbit.apk",
                     "FitNotes.apk",
                     "Five Nights at Freddy's.apk",
                     "Flappy Bird.apk",
                     "Flipboard.apk",
                     "Flipboard Briefing.apk",
                     "Fruit Ninja Classic.apk",
                     "Gboard.apk",
                     "Geometry Dash.apk",
                     "Gmail.apk",
                     "Goat Simulator.apk",
                     "Google.apk",
                     "Google Calendar.apk",
                     "Google Chrome.apk",
                     "Google Classroom.apk",
                     "Google Docs.apk",
                     "Google Drive.apk",
                     "Google Duo.apk",
                     "Google Hangouts.apk",
                     "Google Home.apk",
                     "Google Maps.apk",
                     "Google Meet.apk",
                     "Google News.apk",
                     "Google Pay.apk",
                     "Google Photos.apk",
                     "Google Play Books.apk",
                     "Google Play Games.apk",
                     "Google Play Music.apk",
                     "Google Sheets.apk",
                     "Google Slides.apk",
                     "Google Street View.apk",
                     "Google Text-to-Speech.apk",
                     "Google Translate.apk",
                     "Google TV.apk",
                     "GoPro.apk",
                     "Grand Theft Auto III.apk",
                     "Grand Theft Auto: San Andreas.apk",
                     "Grand Theft Auto: Vice City.apk",
                     "Grindr.apk",
                     "GroupMe.apk",
                     "GrubHub.apk",
                     "Happy Wheels.apk",
                     "HBO Max.apk",
                     "Her.apk",
                     "Hill Climb Racing 2.apk",
                     "Hinge.apk",
                     "Hitman: Sniper.apk",
                     "HP Print Service Plugin.apk",
                     "Hulu.apk",
                     "iHeartRadio.apk",
                     "IMLeagues.apk",
                     "Imo free video calls and chat.apk",
                     "Infinity Dungeon VIP: RPG Adventure.apk",
                     "Instagram.apk",
                     "IRS2Go.apk",
                     "Jitsi Meet.apk",
                     "Like.apk",
                     "LINE.apk",
                     "LinkedIn.apk",
                     "Lyft.apk",
                     "Match.apk",
                     "Mathway.apk",
                     "MATLAB.apk",
                     "Mercari.apk",
                     "Messages.apk",
                     "Messenger.apk",
                     "Microsoft Authenticator.apk",
                     "Microsoft Excel.apk",
                     "Microsoft OneDrive.apk",
                     "Microsoft OneNote.apk",
                     "Microsoft PowerPoint.apk",
                     "Microsoft Teams.apk",
                     "Microsoft Word.apk",
                     "Minecraft.apk",
                     "Modern Combat 4: Zero Hour.apk",
                     "Monument Valley.apk",
                     "MX Player.apk",
                     "My Boy! - GBA Emulator.apk",
                     "My Talking Tom.apk",
                     "MyPlate.apk",
                     "Mystic Guardian VIP : Old School Action RPG.apk",
                     "MySubaru.apk",
                     "Need for Speed Most Wanted.apk",
                     "Nest.apk",
                     "Netflix.apk",
                     "Nord VPN.apk",
                     "Nova Launcher Prime.apk",
                     "OfficeSuite Pro + PDF.apk",
                     "OkCupid.apk",
                     "OkOk-International.apk",
                     "Opera News.apk",
                     "PayPal Mobile.apk",
                     "Peacock TV.apk",
                     "Personal Cap.apk",
                     "Photomath.apk",
                     "PicsArt Photo Studio.apk",
                     "Pinterest.apk",
                     "PlanetFitness.apk",
                     "Pocket Casts.apk",
                     "Pokemon Go.apk",
                     "Pokémon Go.apk",
                     "Postmates.apk",
                     "Pou.apk",
                     "Poweramp Full Version Unlocker.apk",
                     "PowerAudio Pro Music Player.apk",
                     "PrivacySimplified.apk",
                     "PUBG Mobile.apk",
                     "Quizlet.apk",
                     "Rayman Jungle Run.apk",
                     "Reddit.apk",
                     "ReFace.apk",
                     "Ring.apk",
                     "Robinhood.apk",
                     "Roblox.apk",
                     "Roku.apk",
                     "Samsung Calculator.apk",
                     "Samsung Email.apk",
                     "Samsung Experience Service.apk",
                     "Samsung Gallery.apk",
                     "Samsung Health.apk",
                     "Samsung Internet Browser.apk",
                     "Samsung Keyboard.apk",
                     "Samsung My Files.apk",
                     "Samsung Print Service Plugin.apk",
                     "Samsung Push Service.apk",
                     "Samsung Voice Recorder.apk",
                     "Scribblenauts Unlimited.apk",
                     "Scruff.apk",
                     "SHAREit.apk",
                     "Sharkee Browser.apk",
                     "Shazam.apk",
                     "Shop.apk",
                     "Signal.apk",
                     "SiriusXM.apk",
                     "Skype.apk",
                     "Sleep as Android Unlock.apk",
                     "Smart Tools.apk",
                     "Snapchat.apk",
                     "Solitare.apk",
                     "SoundCloud.apk",
                     "Southwest Airlines.apk",
                     "Spotify.apk",
                     "Star Wars Pinball 7.apk",
                     "Starbucks.apk",
                     "Steps.apk",
                     "Subway Surfers.apk",
                     "Survival Island: EVO PRO – Survivor building home.apk",
                     "Tasker.apk",
                     "TeamSpeak 3 - Voice Chat Software.apk",
                     "Telegram.apk",
                     "Temple Run.apk",
                     "Temple Run 2.apk",
                     "Terraria.apk",
                     "TextNow.apk",
                     "The Room.apk",
                     "The Room Three.apk",
                     "The Room Two.apk",
                     "Threema.apk",
                     "TikTok.apk",
                     "Timing Hero VIP : Retro Fighting Action RPG.apk",
                     "Tinder.apk",
                     "Titanium Backup PRO Key.apk",
                     "Torque Pro (OBD 2 & Car).apk",
                     "True Skate.apk",
                     "Tubi.apk",
                     "Tumblr.apk",
                     "TuneIn Pro: Live Sports, News, Music & Podcast.apk",
                     "TurboTax.apk",
                     "Twitch.apk",
                     "Twitter.apk",
                     "Uber.apk",
                     "Uber Eats.apk",
                     "UC Browser.apk",
                     "United Airlines.apk",
                     "Venmo.apk",
                     "Viber Messenger.apk",
                     "vojaGO.apk",
                     "Vrbo.apk",
                     "Waze.apk",
                     "WebEx.apk",
                     "WeHeartIt.apk",
                     "Wells Fargo Mobile.apk",
                     "WhatsApp Messenger.apk",
                     "Where's My Water.apk",
                     "Whisper.apk",
                     "WolframAlpha.apk",
                     "Word Search.apk",
                     "World Series of Poker.apk",
                     "Worms 3.apk",
                     "YouTube.apk",
                     "Zillow.apk",
                     "Zombie Avengers:(Dreamsky)Stickman War Z.apk",
                     "Zoom.apk"
                    ]

scraper = PlayStoreScraper()

def apk_maker_file():

	for i in files_needed_list:
		first_index = files_needed_list.index(i)
		app_name_input = files_needed_list[first_index].replace(".apk", '')
		app_id_output = return_app_id(app_name_input)
		app_permissions = scraper.get_permissions_for_app(app_id_output)

		with open(str(i), mode="wt", encoding="utf-8") as myfile:
			for index,element in enumerate(app_permissions):
				print(element, file = myfile)
			myfile.close()

apk_maker_file()
